---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: liqo
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: liqo
      version: "0.1"
      sourceRef:
        kind: HelmRepository
        name: liqo
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
