---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1adupcrumesecewatc75ar475g6qglykls5sqd38ukwff594cfycquntrer
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1adupcrumesecewatc75ar475g6qglykls5sqd38ukwff594cfycquntrer
