# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ubfkiTrsR1dHT1ClJU2+M85NGzhPI/hMwg==,iv:WHtLs+RsZDPvAzjn3mcNzJu+tj9KGq/I88amsVXRejU=,tag:lLKcCDZwXcCLq8kiB4cU9g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:laREEvqfhiD3plr9jVbooolOqled/XKBtk/wkDlOeEURckGJkQ==,iv:0ky7YxEkB+lB+dXkprIdAS9aPsDD7EojDdpSDwTiN+c=,tag:d0hQt9RXwZB9kxd5II28oA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:oxsnmRKrAerTjBK54A==,iv:eWaGvf1IE/Lefj00j0o4hgC1qYSZwymqlCgfzhxmPs8=,tag:ts1t8uieiNmFUeA1dDhj5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSm1LTmZ6d3BEM1AvcFd1
            M01CUW9OZHdQdnFjZU5tNHUxQ1JaODJnUUNzCm91Z2FtUExyMC85cEVQOWNlaHd5
            ekZmTE5XWUExOHJmd2JTN25PdWpoZUEKLS0tIEtXeitxN2laT1dpSE1MM1VVL0VM
            MUVqSldNTnFNWVFHZDF0RFZnNmh1NXMKna7BRJKIIJq7q2aCWxVV+sIasIImAQ7R
            wx/SEoSmZCSAX2w5XslJlEFE/Mc5pdausf3TdcTghqMmTgd0/jsXpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T09:14:24Z"
    mac: ENC[AES256_GCM,data:v0dZ+/162VeqAKPvG5UvSaWy7wTuZyg/WtVt1bn5rC9UcAEeYyW7VkHxAvZ2dSEbg5MICvli4m/jV+Z6JhjOZhOiV6DarV9Aj8YSHf5OjqZdQ+AhRRWAkOhTuDsYUb3RPqaF8Zrwa46E0CfXVGdFSeJPt2RmMxy4WrCEKk32O5k=,iv:3RF3WE0zjojNfZH8kqhfeIuJ03z101aYt0Unl1F9wDE=,tag:GXRtEAL48SmsMW7A8Al3EA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
