# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gdDmruu9rZUWrIIV8GbmRsCDNfLuz/DQbw==,iv:MRFppt8zQKhtve8fqGcd2Yk3tf43uPWR+CRQQ7/42pU=,tag:nUs/fHMibsJCluV2ZqYgtg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:UUmU8QOL4RnLECd5UaLTj7pL8ZX7BiO6DXLmM2pDgmkzyKz5fA==,iv:GQq74K9FuKl6foGMf7ycLOgQOZQ7NtT9BrEjKykvjaA=,tag:fR2BjT7JHQCvqOWheTw4dA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:bDW5BlhM+lqhDR2dprc=,iv:JZs4ESJ782DIKA2LTCYxxdXA/ZsLBsQy9whhfx6t8Xs=,tag:yyvaU6RMtEriYi+rnP2aGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QlFsYk9DSjBPZVVOdFNn
            RVgrZWh4bGUwdFRlMFZVNnFGenQ3M2lqRkhJClpBdWNSRkFnSlZYMlduQmpXb1RK
            TE4zQWErdGpxVm94UitQVUlJOGJ6UkkKLS0tIENYeTRnWkpqVWp3V2RQS2ZIakw0
            MDhXeW9qV3h3bk1FYUpISFdPSExtaWMKZTmDKn21E0XPWIbosSdf5V/dd3evuRxc
            eRFplYh7L87j0t0ybhwkxK02ejoOWhPhWctYY6//Nkl2afsoJRKT8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T14:22:54Z"
    mac: ENC[AES256_GCM,data:0Zpq3kDGi97E9jJ8u9wUBGMgXK1W4kvlOJfPJyYvdx50Zz/F6vuVoMu7pXsQ0wrUtc7VY1Px9d0KimEuNzO3riXATJojnrzCZndQl5TiZ5wuqFGFdwfHo1C3ycfxOuVZuShXTlXULIXgR24NdAtl7qGJPCV5SxtKZbuVi4nOs6w=,iv:956OWcgtWGcq2NPYfYH1utVgTpQT8XaETyWT534b7XE=,tag:yW2+zHZ8mJGdqcf4VrT3vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
