# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+osNbrDC5uQ3SlbjQIcXxbkqxz7cnvR4NA==,iv:Njowbk8slPGxyZueFIssox9/YkyLhP0AI2jfppbgJzg=,tag:DcoEdj6B5u8wvNSBuGDN3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:i2UAnqsjL8u57DBvv1DxdYsDqPQ/N0wfPuANrw5E/7MAHE2onQ==,iv:ADPIQ79I+YDYaxd2HMb8i8ti/O8Vswd+IGZIzxeTOEQ=,tag:jrYk2Oq/9H+AZ1cHdiCjTw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:kBhzgzXPl7Q3yndYhA==,iv:plqEE0wZHj+gd9g951BPsF67eCt0EbmO/pJRJ2zLNC8=,tag:Qfs+7Q4ZilFOgVuMUml0HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzclNGN21WRzZEY2xSNjNv
            Z21qdThUcVFXbUIvYkkzQU4rVHdGWWI4TEM0CnE4ZnVKMDl4cDExSEJNMWZrSitv
            dnRVRWliazh4bWhtczlBQ0syb2dZSlEKLS0tIDRCN0E3cDZ5dWZIK2c1dmFTTDl5
            OUZra1M0R20rWDJVd3liRDA1Q0VxMDQK6hgtgu7kcKFNYeLTWuQO9SOsAm87UZLH
            eVe7sTLY79XYpnwJrXsv9OB0Zu4IgC+zRlss/hbfkBdfInOCEUC67w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T18:26:26Z"
    mac: ENC[AES256_GCM,data:HpfMUcTvVnL3UGTO3UgM5gkvO3EWKxYP2D3FM8OQeOj6ttCcppmkfUAIzUWo6H/NYLmY+eifPIFaOLl1t5ty1mag+fgnG43YbKpx3P+YqfVCLzDQ/yHL8QTnvU6/OGLOXyB+Ybg1wdUX1uE+Y/pwa6jztGvcagzEfLBQoSFgmfE=,iv:3eNatsy8o9nFcnA/CN8ArciAk1kLxdmXXzD80MMGVjI=,tag:HNPNaqDL8xQlq5xDiC1P5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
