# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3y03xLOyBJoP5tPbUX66knmtnS7jszvCtA==,iv:LkPNZeEevP+cqtLcmLKuvXQP8WaNr857CqN69MuQnPI=,tag:+GjATOgGghVthPx9vpRFoQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Auflb/3Nmoslzx+8xLaGKHjHmSkn0ny0YgOy0DPJ+hw36HjQ+A==,iv:VMkAL3HAnZsrx5XM+HMHGHp4DP9rUaHhlQncbhlFJns=,tag:/1eoXXkTzZHsWOVy2IyQ8Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:FtciItdV96U5/QVCxA==,iv:TUO+GtoHOE0r5e6J1qaCYMwyyzKT9YwaxGSJwtheCQE=,tag:76hBuU1Q9CKzV/qCNTMhnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6emNGQzNSWFF0RGFWMm11
            bEN2eDB2WjdiN2ZYV0hKdk1WalFSSFd3UEJnCkRCaG5HUW9FQU1ZYk1wZUIxaVE1
            TjdlZndNQ0h5cUx4TzVkUDlwVXc3Z0EKLS0tICtGVnJ1Y1d6dVFNWktqa2NiUEtG
            L21ZdU9qdGxLOW5qSUxqdTFWVEtwV0kKO+vqZja1+9XTbylvL+HnKLeTb8bZbqA5
            Tipxy4RmHKH+vXBZIb1LOmyI3va+N+pb5asG2TP+yx3r1eWTnl5Qsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-18T18:36:07Z"
    mac: ENC[AES256_GCM,data:A2q1qgfc8gijT5qgafSw9BR8EqK5Ezse0FdYLuFIWHqnLx1Y4XUv1cZqdTtFxuGq7OvIewSmUvso+qTNvm04XU1p9jg7MW7IzZjMD231JqFbxUAC32/pp40DrQCVIpO26JvAv+Uor56CC5hA4L96IeBOCTRDF97izQKeQLXouCE=,iv:EmrKRrIQ9bkjSeBUg53FPwk69f210CkTciBJpy1rTZ8=,tag:KwaazAxYP4/IC+RN/2UmIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
