# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:1J0wa2hromDMYU9UGsxlkRDbbUiOBrJiGA==,iv:vllZ+9SF2L8D5RKaciwqDqwhXzP/EDAPVzviSItS/3U=,tag:iDr/F0UYqw79pKVHWh0qVg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:F0UuXAvSULSiKTPu66YFC/pcxhvyn4umW+VwM8rG/bingzoOkA==,iv:keeTIq7bCfSjYjzZ+xPAhJ08aOyzVHfTy1/Ryrpev0g=,tag:xGx0fJANRn63y+buypX0jA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:57HB240tHchIUanK0w==,iv:rlr1pNRUwY7sn4b3gNWYDViS2zpWtU35DRRTl+d9Zx0=,tag:w9ovgkRFhpYUZBwMxOJxWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb0JicUl3Vmc4c3A0dEpw
            c0YrWDVVNnNjbldVNVNJQ2ZlaFM4ei9tYTIwCkp4NmYzV3RPQ1VSc2tFREdTdlgr
            c2o5SGt6NFg5dVdMNll5TlZwUi9STkkKLS0tIERKSXowbDdPUTVOd3NyYkh1a0ZC
            cDBHaysyUUNsaDdRWHM5RGhkbDJGcUUKOMkyicRmPDzsPm+QS4jOtfpom53W0VBK
            /I0kXmBzE7U16dQ31JBCzpQxTUju99pBJHlRSqZz+skxRQxwyliFCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T13:42:25Z"
    mac: ENC[AES256_GCM,data:NLwx2lnY/A+KeJp8UridkwcwncC3kKiEamwHO36rxHypi8gBPHeYhbIyd15qAtyp0JqPC87aSgWpe1QJMsS/DjugntxhiEGBEq0+T5dFLAntsDhZiXjjUrI4217p5FZxBnnNNpFu/EYnY8I1c6MfL/BK5FWhYb7iWEJ305VxRqI=,iv:RxAq35dq/duO9ae0Nbx2EWSAaI5PQO1CsYOJeRCEX5o=,tag:djcWBQUIbpoR437wdmYlHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
