# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mzwDpSnNpz7Zh3jSNNAgpYxc/DmBTcWX7g==,iv:hn5kJpT17kWdFQQ38KxY9KCe9CHPaBUaULB9VN8wON4=,tag:gjt0rbxz2CpM3Ef2yxXnCw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:iGVG6RsXswIiZmg7VHldjt7C072GscvcRm6yMLwim8MqYg/hGg==,iv:7EXPjzZJXWGizZGnmHY2GkoWfJdQ0IWoj2ncFrP1drc=,tag:gIRG8Ki2qlQeFculqL6OIA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:exYBoAVKvJe+dehLTw==,iv:I5mEAhjGXrsi2Ja/mX1vJmq2esgIFHa5GkRxONUCr2g=,tag:PrePW1lca0E6x9cZZD/7qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SkV3ZmFCUnZUenVSNTd2
            OTJPWm9iYW5ZYTZwbDZEMjA2a2dKSzlVN21nCjVTUVBUM29MeGZZMUNIN3JkeitH
            Y2RyZGwrZ0FUSXNqLzYzaWFBeUpVWHMKLS0tIHRQQ3IxckdjeHhTWmF1SURvTmYz
            WHBzMURpcXJCT1YxcWF5aUs1b3JFZkkKobFz9YgNvQ21njYGcgSztR8QgaGNH8kC
            GOFIJwDDIrjIACpVxLYndFSeUubaFG1DGDlWN57atTdcETaiarS2jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T09:40:49Z"
    mac: ENC[AES256_GCM,data:THfddcEUIsrWNSWU20mlz5Ro3Ypq04kdB1FVV7uy7hAJB5pJlrrsqLzvTgdTNcR3LOw1LycSkEnt2RCrg12OBfrpkOTYEv66Up53AYvjxjZefYovn4lPNGaXhs28QaxvcieWnvEClBJohCTqmdsl7705feYIWddq+U+yCIkkVYU=,iv:bWwet+Rd4JqbCyvyaHQZq+sdBBeESLKy8y88W8Sy50E=,tag:7Z0bHQdkq+mfmkdPzqkvJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
