# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3nZUTYnHKhNw8VQPDmnQ7U23HC7WfuzdMA==,iv:iZsJnjrKaHzAvsxkiiOEe8Lvjv+JQo8Cyw2JwluePEE=,tag:hTz+zvl7W1Q4GVrKFMYHrA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:SdEg4mOhR3vPVmQxa5+EAUZlCcCs+EaXP3Ni/lkLxDUKk8ExAg==,iv:d/97flLgQUfa61yuq2hI/HXI2DBVhmsYnpmjNseOIu8=,tag:oQ5Aajc6fJlYSGXO3npA8Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:7vDm4GqPFcv7W+Bzug==,iv:8YoymvxpEs91ptkg0cQWleKuEMnrTYgCxPNvN/WNVRA=,tag:O/Jfzgxi1p1filrQJANYxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adupcrumesecewatc75ar475g6qglykls5sqd38ukwff594cfycquntrer
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySmtpVUNsTFF4SUdocGZu
            QXZjalpFdEZzNmcrUnpYTHF3V2xMRnBZR0c0CmVjRklPMHlBOUdiRWJSeEFra295
            WExWMFpjMTlIQlo3bW9OOVJ6ZVJQVzAKLS0tIHNLV05UUlR1ekdTbC9GbC85czBa
            aFhEY0s2T3VzaERISWJmeHVvbFIyYmsKQxST2B7b5WqWQGtkXc6ES7JBMiNezVvH
            PiAxxmccxXjozO2RxICqyba45WmpUryywnj/jWinL/MTLEv51dDZew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-14T10:28:28Z"
    mac: ENC[AES256_GCM,data:MyJOIIwuiP3a9FazfzPmC7quTv8J4+GfsbBONdeQEUlDVpZZ47PfDcmAGbWDjob7y2Kg0/58b/RPBJzX5jAtn1YOqgA7+vOlc5206aJpzV4E0b2BswIFtOUbxZfIkKvsBdck1xzSdNH7jxvrdA6S4Z9DauSVJLeShfXCrxK0cbQ=,iv:T4StaajH9GmwxiffNln+67OMcTamVKvCVq5jGr527S0=,tag:qnKQuSD9sCAfkHW7I0jRjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
