# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:qialPZXIqN5ZNXegN2Puo6Qf43pjtsItb+DdkTyw7VsxZc7oRA==,iv:0JOpMFFrMld+ElKAEsTyORjbNJCbDbnuJ6QdhYA6rF8=,tag:FnKDBbZn0GopVVHXBS2FMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNUVaYXFFSVFyOFhVN3BE
            ck9Ba0xkNVpvUmE3STZHczIrN2lheHFwM3dRCnVYc01GVWdvL1M0SGl4SWpYem5W
            TkdGcXB2aUFidlhsTFlEU0M0ZmFRRzgKLS0tIHdUck9qVU8yM205QXF5a2tyMzJW
            U3VQSE8zWFdTK1hneXpBNm1lQi9OZlkKtFQMDJof1rr5of9m7Ohe9+2LkuKPPQZZ
            eRk6Kq8fPHB7Yc9sKCo9Gq4gS9NTV233w7aecBgIevwK2UuheYPUzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T16:29:49Z"
    mac: ENC[AES256_GCM,data:ZOpoIbB5W1tZIMReBvUjYCmppHUCnX5/3kXEwCXKwJ7JukHPOo5WaB6Anco2bTEjXhNt9cpPrjQ4EpDChUc3QQzHgL1SsApVOsl3s3mKzan/Vq2a+3lrMLm7+ud+AcDeBxtC+JEQsZiLV264mITo8wo6RIkbX95sZdSws8vXROQ=,iv:q6j9g1yPnAnOpjYYSNR4pPFyEukfDX9q5kN0ZHLn010=,tag:YsZnpeWFiRXH3vjcRJT8SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
