# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:hvZA9slfWbx6z0+ut5co4wO5J2d5tMbqlJIBTCa0YDv8p9gd5w==,iv:AlNUYiNHPfUAoF0+BUqQYFelYouwxrIZdYMV6l+dZ2c=,tag:MrIQzZKeSbqq8etmWtcK6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adupcrumesecewatc75ar475g6qglykls5sqd38ukwff594cfycquntrer
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMk00Z1VHSFg3d1cxTmll
            cFYxVkR1ZVhxbklJV3R6N1d5bGxNL0l2b1ZRCkFweWxHSWdPM04zaXFKTW5XMXN0
            ZzUwRlE3c0NnSXlmRS9YTVdQODJBY2cKLS0tIG01VkMwNHFCRjBJN3N1SmxuUFRw
            RU9la0dQd0J4Zi9Cd3huQWMvZ0N1UUkKQJo/pOLsKGeEm1Fle27hLzjKSBCEEaG7
            5ETr1ym09yPtCfu8qkylXSABNCGXbBi4O+8ox6exPpG4JiNam0Kr+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-13T14:58:56Z"
    mac: ENC[AES256_GCM,data:jSNQmDoxnhXnbBP4gt0ru2MpBq60VkbgKas9gSzTdfKETSfFHiFE9kVCniqYZW6msTr1u3ui8b7MM6TtpydbN5GFG/GW35MSKmmF1aRCIPT1b01hZ7WPvUwvKYCNRxIJalgT+iYDW90Q1FHFGhXcs8zjVHOfCgz+4EAtmemFJaQ=,iv:q6DTYui+ali92CVBk1zPd780mHCf8+oH8/nEWsXnY4w=,tag:gXYPKkLFea9188/uMfiMbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
