# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:3s9dbUqIFbPFpbTa3JGudOq4JqqNNKIp/I3KrLIQxCzvx9y7+Q==,iv:VwlnwKuLj7kN5Svl1XT8RkrkIKgR/kYyPya2KsA3x4s=,tag:UQXdwldnhkqCoabqtWU5jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2VUdEJRTEtZVjlNYUNz
            aWY4cUl4RGUvbFJ1WlZhaFhxdlRlbGtUZ3h3Ck8zRGhaTFgyMmcxZkNGTmt0cmNu
            QlRBa3JuVFU0YTBsRjYrRGtDbWxkSDAKLS0tIFNIRklhc0x3eHQ1WEtJdnNFV1Ra
            VHdjLzN4a0oyOGRwcUxpUTEwQTFJQmcKl8OaPHpBo8VIpYIFexCe0MYyxYO0t52L
            v5l9QUrovc9UAoXz1p3Icf//OzZN4bbCqPw5+Bcny7zlnTCo7xzJoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T13:42:25Z"
    mac: ENC[AES256_GCM,data:yZZ5ocEfrALLwQWZ57J/tZxiJtxThq+NsGqB4R/BqY2Rze/daT8rkVYbsG1+qz2kJrtuKdnJHQTQVsXrxFhL2X4fhSGCSU/Mk81V6wpbDFkhHbD2f6BKLLLB/acewTgw9y1K3MApZ5qcW8mXYDGW4otqCKQy2xQy85kONqadTf8=,iv:HpEDcfAli5InVrqkR1g/yEz81DNuqLfVplHlYpYLMz4=,tag:sYJZl4f2iEGMDRe/v8ngWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
