# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:gIKY3CwpBRNuCAddXHc9GFpGb8E/ANj3Tg==,iv:C2lfQ+ITwXimnRu/aqPJgdTk36aLiIJITXWVZL8M9CY=,tag:psQBRUHuuYuVSj088Gs/uQ==,type:str]
    api-key: ENC[AES256_GCM,data:SjnysgPawJEulhw4xHqXhbrXk0ecMM0MoTSYJOUmGSzBRBAusg==,iv:g+UkizSkETUi0Fk7vWoqZht+Hht/KhxAslJ2a1TYu0c=,tag:ZH8VBmpz2oLXKodgPzuZvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK0xmbUcrc1RqeEJRdVpM
            bWthTWRNTksrSWt2QktCUHpTWXNQYUxKZXhvCnM1eTQ1NG9oaExvQ0VMQWJKVE9i
            Y2xEcmxzVXhsNVZsWHhJTXptWUc0QWsKLS0tIENuZTdkRFBqOWYzM2FLZ3Z5SGY0
            Uk0rNC9NdEMyUXlHd0hVRmd5QjJNaU0Kt5UUW4iISww+tlDySntke+pTn2k6Z408
            O5+K77pf9LqvuY7m0TmwWLuSRKVe/blnmNPss8ae7FlI7hBsSFn4vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-18T18:36:07Z"
    mac: ENC[AES256_GCM,data:h5vZZt3POVNq4duDGQsXDzei0MgEQsdatJswseOrkobkEbilzZ8t7fxN3Xw1yYuQEw8RlOnRHlVKlpCsg3CspTgxNhY/1OUhEUOeblJR3f/S7iwTob3jSLppkkjsIx8+HZp9so2WJDCV8sX/quzVJ0RW52zjjSw5yFkz4nGQC7I=,iv:dySIhLR473T1vHNMKu6FupDV6O0mjR+VzMK7Hrheh3s=,tag:szR5W5U5MlbEP83g1QP45w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
