# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:DJDB4VW4lNAfyUJiAygmJfzoClOy+nIBjQ==,iv:RR/46bXzUb1OMKB20VpHaLotgSKC6GOz01U9pd/dmrA=,tag:iDHyF5A3n1S54PAXusch7A==,type:str]
    api-key: ENC[AES256_GCM,data:xDKAKykdzlfCuVqMd6cVg9tqUD3hhquKG3S8tZlSY/0I4kWv3A==,iv:bBViGC9JpvhGo3ySvS+ypHKQGotD0yIYm0VXa7CBYWI=,tag:Elw/42ZBXWsL4W0fNtSdww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eTZYczRsbVBtUksvdUJj
            MEdTL0xUdXBCaEFJektrNEFQcmdPYXdvK0VRClI5QjZKZmw1SkVIZ1d2SytIK3JV
            c1BlTDZtcHhmeUVVbzdQMjhRWEJYS1EKLS0tIEd1bHdoUm5BWHoyOVg1dzhjd09p
            Z0VuYlIwcVhqQXFrd2pncks3U3ZoVW8K8aJbTxvFH343h8yA5/yR6MgtcdmRkZCk
            SousW7VMo34aN10y25xyTyp4Y7uqUCT9SqU/+qGauZ10eGxyqXqt/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T09:25:47Z"
    mac: ENC[AES256_GCM,data:z+0sED3HAZ9e7orlR0TbT5O+lxhXd1jCXlZueQktuXbxPuEzmcocIChfCpdGc5TtgvvQD3WaewUHTuVF9N83g+1/tEYoCk9sT9Co63h4Azi6JrnN11a7oypqQggWdPQvElmP8qSLC8kiWWS0AaXRQRme9ELu3Tyl9fu1kXtaBpk=,iv:JQBxKAq+B027bKY4vwqpzh2sldtSd6thr51zvJcxUUE=,tag:b+DJkj4RTJIRwYr9sQF2UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
