# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:q7cRxGEeIpPgoApSJNzxnmUhzcXi6PWVkw==,iv:l1g3iv3nRGJi+xjMYgW7fK63vCaMKFromrKHxaz45Ws=,tag:iml9LnPTsAQyB4bQT5gSHw==,type:str]
    api-key: ENC[AES256_GCM,data:sE93uFv2q1saeO6V9MCHAnDhQoOOebb5MwvEV43Uiy64bj7p/A==,iv:lJYSz/oa4Jr1aEW9hd5pbcXliXUrtcuUF20zKcNSRgg=,tag:qrdL67w3a8JA4a11ueSuyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd083RFkxa3F6SzVBVDBh
            OVMvSTZldVBpTEd2VkhkekxOY3pZdFZvaUFRCkR5aHpWRTJWelQxbWhhZUo4U011
            eldPM0dsQ3hGWjd1bWZkbFEyN1UyR0EKLS0tIGpvMjJQdmZtS0o0MTNqWGNsWGM4
            WmRyMG50Tjdjdi9oS3lXQ3kxUmtlQ3MKwzLls5HD+XIbJH/LXq6lJJrXgODJ/rpp
            eLfoiK6TTSiBwfEGWsRPpCjB1HmGivlzkobOFPLsAJ2b5BiDoswTdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T12:26:16Z"
    mac: ENC[AES256_GCM,data:9YLmjGHz5KxKg9aoQSsZVo0GUrBxJ0GAA8ULAs1jbfHmBWWLknO0aRG5wqY3Gkswke8KfG0LM9AGt3RPi+6GB8I3GnNIhaMZ0G0x2rWYunG5LhaDLZOPmA46LcFycVzlURtBmuCF3PxB+qbFF3rIKkzb5po9/7sfexib5AexwyE=,iv:MPGpxM7tz2oANlc3Zb0SQn6CITX7BmqIocRkO11W7Uk=,tag:r6CjS4SED6hW1EopBuBoKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
