# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:hAx6O6OUDY4Rf9ry3wSvMKpZs8+yeY5TmA==,iv:+D8QpbDaTWffZsOjyvfXhGpFgRdU11CmFkIMbZg5dKc=,tag:cloO+ef3OuYNK0Ut1eZ1rQ==,type:str]
    api-key: ENC[AES256_GCM,data:xZ+xynmMsryFU6d1/2c/41W5334KQaEkzehZmcTGwnDYET5etQ==,iv:iY3mumMZqXi8GCPv10JpuxrCo5q7PK19HTslr4cXCQw=,tag:ETpAdKcYXpghVLtO2hbURw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZWNOdU40dHRNUzlGNVNM
            RXp4WXdpOWozdEkyTGFWNmRiSDZhVStNY1U4Cm5qMmdQSWxCWlNNYXVGTDVuMnlR
            VXZESnIzeUZCeU1HcEVFMjVCN2ZQRk0KLS0tIGhsRURDWVhIdWphL0EvZ28yWXRQ
            REpEOGNidHU5Z0tVa1lTQXBYdS9uUlkKwMlc8zPJJnZ1+aKG6kRZunLfKIyyeywr
            aoXQ+RmH75nCeHof7GczXFDLEDcQUIIQFzsMHFoOyYhmCCO4mwErqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-19T17:36:31Z"
    mac: ENC[AES256_GCM,data:fL2zBnFSUo2oCE9vEv6sdfjKEbm2XlN5r2arab+yZhpLlY4snK8qspynOYglNK4Un/tJrzDRoC30xyTSFh3UR33IuJ86N8R2kreafZRAg7TDcvraKeTz8S3B9g5629TcRAKI6qaWMpx/Vyw/IMADiCeetRvBKEdwq+RO44AndMs=,iv:D9EiRaWxp8izHk6J5CgPkhQ7ForbnNmtxuc8v+tDtMQ=,tag:EXdSVyKAdnl9PPT7ErTP3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
