# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:dhK7LD8+aH0gdirgmledVcfzc9IPVUID7A==,iv:Lbvax+q2pBlqtz3TvGS+w5pVsk2uuR1szaEVu2dIRyY=,tag:9ZMbJ8Txyu/HMPCmI4EwlQ==,type:str]
    api-key: ENC[AES256_GCM,data:AAWbd8l/aB3anyamAb3HPf6LhtMdhQCnyiNdKHEM3FQR7wx2sA==,iv:cGly+o/tYRMZ/EkRkWpr/41GFaGnOiW8fkVZOrxudm8=,tag:Dl0z2vgO6gCJU+NipoDRbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzM25mWFRuR01sMlpQWDVK
            N3hOUlhMQWM5ZVZqbngveWRuSHpwM1c0dTAwCmtXTEhnK3ozVzZHU2thelFHa011
            V015MUh2NEY0SzBjNXd1QUhOaHM0QWsKLS0tIEh6ay9BU0s1ekdMUFhQK0lBWkxC
            NC95a3l1N2lNcWFqdTVnUjV1Z2h1U1UK2KKFe6ukCKpiKxfKbLApqGhp6KsW5+Sq
            QyG/F+Rm1uLS5QegGwUN2RFpyjN83DZfsRFA1oVPtq2PYtDbyBTjgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T13:35:12Z"
    mac: ENC[AES256_GCM,data:iBcAyDhSDKv3TLe82peOCAv2xgVvORR9cKooJWqmGK2xEEu4gmmvrrLO3K2ghnZVnE3XL5Dc9TignJPlSbw5dw4uboM0lmtUeBlETdG386lrMdK/7rkDHdFmFKYZXNqI5A9e0G33Wq4yhk+lxD3madQ0sya7dO+W/MgmqhtxCPM=,iv:oy6ifG/dxlviU3uDPptUOuPqjnqBq2c9w4kumcHtIgA=,tag:dj2EvzHmVNmKtSO4nl/bZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
