# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:sIZA73awJHrCGc5e935H+96WGurLkPlbFw==,iv:UgwtofblfU+ENaZtOjY/lsAkJY8xgh18UINe2b59/oc=,tag:RWTHvThi4lg00u8fDCdT2Q==,type:str]
    api-key: ENC[AES256_GCM,data:ThZRKGtbWR1E4Yvy4kbQOI4qCIfdLCoXnw5bXuHBoN9b5vqcRQ==,iv:K3rdwvHbWKb0nSWV3Mwu2dWTkWWNia8ZusbkoXjsWvk=,tag:UkZgVl3F4Gow4+YFZcp2Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adupcrumesecewatc75ar475g6qglykls5sqd38ukwff594cfycquntrer
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N3VHOVdONWU4RWx5MU5j
            aS9Lczh6M2QxS3U1bUxsUDVURmJGR3Bvd1dFCjk1Vm5iL2VwdENMem9XaUZCNGpL
            Y0hIWFFKWDQrVWFxZkp5aW5DL2hTdDQKLS0tIFJsVzN5ZEhWaXhBaHpHa3ppK0Np
            Ukh4SmZveDE0U1Q2VklnUnIzajFpemcK8lwc7cYhA94jd1tFE6HOSXVyihmy6vuG
            WlS7tVQjZbFoAltoj6GEhjU/K5O4ladFbkEiyDCrvo1xvi6SNcrk8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-14T10:28:28Z"
    mac: ENC[AES256_GCM,data:Q+xxyE3+nO4hHANHJeP/d4VBkGlCtSdYZ1fGoGY50IhZkpi7TgpdVKCnblsXFGBIiN+QKPahi/Rq5xaZdFWb8LdhjjuByh/gese378kK0uluXIwDXAsC8WzTyNBcLmrXJvhd1yuB6RlXhRk+mptM2UdFg/OQ4o0krxbEFh5a7Wo=,iv:4wrDH6zYNzoPbTNDBmLm1QVNh5wzi3cmMSTzNyMp6qA=,tag:cij5kh+lTkNiOFDcgO7NRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
