# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Qu0L8vyEUlM=,iv:6z4+juz+ZqeRCLCKZniYacY+nJHncbj+pOpEvNezuq8=,tag:un8bMUDZLFG4mi9S/okOWQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:B5Ia8VYOx/dKJDSi/5Xf4BNmhaWG3ZHAjg==,iv:3zrJc+Hn6yX5t7+z+y2FVGsPEWSJHuqLAh3X0OfRYSQ=,tag:3OBkct2AlI9eKdHFaxPxtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOW55UkV1VVI0UHdXSEZ4
            TnRoTlhoL3c3QVlSTXhURWg5RGZhRm9YM1RjCldyWGZCcUJHT3UxUDJqWUhyKzhO
            UlJFZU53WVI0OWRMWE1HQll4Y3RMZEEKLS0tICtRNGRjVEFsT2tkNWR5dUtSREt0
            aFhhWmVMMkk3eUhmRjVmWjVVWW9Sc2MKBG+q0Zr3mODnwigMfJrRAWOLVzLwkfRM
            32hpn8HV+cGAVO7aIJsLMxI8ZMj7X+sM/5jhEbqDzfQd0eszMQLI0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T13:21:37Z"
    mac: ENC[AES256_GCM,data:xRR14BfPevuMIoea+lIKn86easgkT56HesC489h+kka+RtWIwUaLWMjKi+v/JmSwE3rGoP8pK1MsMwiVHXW3FyHoZU3CXo+VaaUz4XBKKDW8mH+4rL+F8pTSc2FZFCdUSrqKBGHleW9OSMJiRA52tdknwZpMIdFFa1woQkZ9vNs=,iv:2/WHjiAg81r3PMqS0JPYnRdz3c2/pWmptPW9wYRGCGo=,tag:meeXWzd5cyk10nxauFIycQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
