# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pVZTHwkuhT4=,iv:FWWtr6cMEcgmMlfBzDvipc+Cl9eraT+kIpMbA847cyo=,tag:7jzE6bxcgxlVLE3rcTHVjQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XOsJVUtH/tu/fJsgWICXyJ2bW7TzDbcgfw==,iv:i43crps+ScD7Si5AA/NoEIjEANWVDdbF7CojxtvR1+Y=,tag:xlIE9fJoH0XSiTCpn8CCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1adupcrumesecewatc75ar475g6qglykls5sqd38ukwff594cfycquntrer
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSlZPUkFwUW5aWHFwMmFj
            Zy84UVdRbTE2NndXU0lsWGpSWEd1bmdvemp3CkNSdHNBazVyT21vTXprZzhReVpS
            SlU5V2psT1lNY3lmRUZUbDZaK1V1dlkKLS0tIHhjMmYxVE0xTCtwSlhtVW1BcDZT
            OFlPUTRRbDl5eDRLVWNVb0pycExLOVUKpOtZaMK4DU5lav6QfXpNUyXBRR1jBM2o
            vV3HOsvyM6+bj+bRwRQS+PrcJNaU0loA12aMPwkZJb0ciwt/C27dgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-13T14:58:56Z"
    mac: ENC[AES256_GCM,data:5xtNNTYBlPxf44v75HDexEBIJj0lwGyTxM39UbnmW1zwg6kS5Cc5RL7g4Q8f08AauDKU4/FTN3DMvLVER/K0uNxr8lPw0z2DQieDfw0C/wxPYbKZFw1Bqt2jqNexlq+MKJ0CpvKz+9H3hlRYoKa1GUsnWzpJyGL32Tz9NmU846E=,iv:suYuCpRaRzMgGmKOU9Y7kL8jBuUihaMgqtKuE1f8uCI=,tag:k2sDkZuwAcu+JaLQVYez0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
