# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iQS51yfDLT9s,iv:QrIsPWIB5yIBioqCx2uf4wxvPQE0SN6CLwZem5ap7X0=,tag:bi0BN+K358MEEcCkF3KSCQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gL3pfb3SzftgaXMCErMAG3eFG4Xk96g2Ww==,iv:+2dPSku1cmm/WKLU/mifsZ15Jo13PvMdYz26eD09mp0=,tag:jnR0mfBh8tK57TANhBDUEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb1VxOStEdkdjOGsvd3pI
            eGwzM2xaalloSEhqdlhXa2J6VUN0YlMydlQ4CkhPam5CYWlCU0RUSkM2bmxnaXNo
            SGFpMmpwdzhiS245WlhRbGdwU0ZoU0EKLS0tIEdwQ1NGVXFReTQxSG1FY2VPMVZ4
            dnNWU2lnaVJUUm5hTmdVU1lVenhBenMK3fAehM5r5Dmw2YOidADffLh0LK6icAl8
            i1122F0dldX3bAwKsP0ErkT50uIUFkCAMC2Jtf5M9dULilow1vqomQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T15:24:57Z"
    mac: ENC[AES256_GCM,data:Pghn45PxyRtGRd8y3lJG4qoEY/mxBhsbK4jSObr2yTlPZ6MSgevVeYiwYxbWRITW6q6sZxdRM1867gSuu2tIouyKIwn9kEpz1Y0Br3MZeFrBxh+xObB05YVj2dNuu2Tm3apOiWcYkN7PRz/LuUC5kSzzq6H9VL5jBMr5AOhjNVI=,iv:xYLcj775szkQRmXeL3Ez4/Dtlrxf6Blfvf3RplZDnVQ=,tag:7C0Zilm6Ns57wIsdp49Pnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
