kind: Secret
ansible_user: ENC[AES256_GCM,data:p4ErRxtF,iv:xbNNhUCzWq63Jta3LNyKRa6i131IKc3937fdYRSobdU=,tag:++/p01dkUKVo4m3a93xohQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:i23sIamrm6khVw==,iv:NdfClriQqDrY4FqKICdOoqnVXbXdWZPZh0BZ2rDWIg0=,tag:uNzNro1JHYA1XID8N6h5rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOExDMXY4ZCtZZWh3OTdK
            UzRSN1BqcUpXTTFlWEhiRUJZTExpYk51SGtvCmhkZGlrSXJDdC9FS2M1MWFUbS9q
            Y29WUWRzS0VSQ3licmk4ZmFkODJCS2MKLS0tIDVuMFdKTzZmWnhla2xIdFR5MFhq
            VlBYRHlQd0RCbGdZWG5jZ1AxempBcTAKCbtnmkvbqMTILExssvPx4css6PVq1hPY
            zQM/cjSLDeUefq3S9hvPxad8l2SAgTWTAfdC6tfL1szNgbuIsODA0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T16:29:49Z"
    mac: ENC[AES256_GCM,data:nGdDE9u8cx6InG+4ewz31GvZI1iVDae4T6MF5tRvEyRr05KefWjLiWUImYNcaYy7DTsdNK0YsWrBcvip5mTCCeDNwXchXCfQGImtjB8swH18XPzBLNK6i6LqBbAdjpg75bFyHGW1jCuqS8I1S3HGpesDHaNTT2Fr08+IwqXoESg=,iv:SIVye5K0KP2i3wh4rRNopkjlfTeU/JObM3sAJ3vD8DM=,tag:9q7r3goTdLhiMibtMUBZMQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
