kind: Secret
ansible_user: ENC[AES256_GCM,data:DZ+x2px3,iv:9RSgmB57QprJnr1m2ocW/gv49Vdt8650M9x+OTNApR0=,tag:1MldXAn1aOxVQ2Av7quEpg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2+4rPNnXqQbORg==,iv:7wnmaNHi4DNk+cz144cL+0uWp7bHEQpsb/mzn8oKYGY=,tag:vUoW1+lhD4Rmd7mJXgvB2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VlhZNHFlZDBJb0tXbExR
            OEw2cUUrUy95THgrRU9paTJpdmk1T2tvVmxZCm9OZnhpMEg4bmtJSHhMOGZNb20y
            ZlBxTUpwQWhZTnRjWlpseGQyRTlWU2cKLS0tIGVVR1NubldXTHFPdHpUejR0Zm9q
            Y2NEQTJ3eHY2YTA5czI3dHJjbUVuVk0KA8JarA7FBM/hgYCqgnOxJq6Pyz1buh10
            Mc1CPgPN4ThG0Lx58FsGcY9Tcq78JUNsXH9CFqv9PTZL4yfc37x73A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T12:26:16Z"
    mac: ENC[AES256_GCM,data:nvS4xoWpb55OSHRt9AoR9H+EvmG7z377jafZSa/3k2BSMagF3ZPWWkDKOtH0ozNziA0Wd52kdLmgAILAoqKPE0dGQ21qaPichQR5C0KfCFZ+Q85Nm/8QbyazaUlGFt54qA2yNPV2ytJPUrGzVeeVLq0YIKGj3B9lRUUAmSOSoSw=,iv:U00iktwCfXu5VfsmIyRaZolNaWbM4+ZyLiGlVER3Oag=,tag:r0MRQxS/L5lCIJgMKL4AsQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
