kind: Secret
ansible_user: ENC[AES256_GCM,data:nfqgEWAf,iv:cu8sqAYkcKLgAOK1QBVW/dZpr75IEsPJzDLK2hFbbPo=,tag:rnmEhP8xYq4BeOn/SXiujA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OkcyLKaYPNKWFQ==,iv:nZzrtI48swkPwaLn152iJAbyzIbqmt0v7eCrGz91rog=,tag:KPePqr/fo+hGEgRDZ1vO5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ3U1TjQzSGpNZnpyTWFU
            Ly92NHhiUDV5b3kvMk1aN3J4aFRZYXdyYjBvCmVpUVZFZVFoUFo2eDIrOFBXR09l
            UW45d2xnU0ZMRTBYM2MvVVJCQ04vTkkKLS0tIGZvUmphZEVTTjJxTDFwck03R2I0
            ZHUyMGNTWUpSOFYrNVZaaDNCZ1N6Y2sK+Rx/iN4KZFPGyqYUUjYdiD7BVj5LNCI7
            MkVCQZ4b6V+7ei6pf5PuMXv2vYOHV0TwH/OJffhBsrBnYhAAU4ObbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T12:15:46Z"
    mac: ENC[AES256_GCM,data:6Dg+alS454UoHZ1V26itt+3t4O+I4l7GAkOWre1oVUiDeIoJKR+JNWKp+4o0jwhS2rfiuVmK0ragywMKlJfVxWf7nJQhrqKB7R017gfA2ruIffz6649vkxti2c3rTCbyWgclCWSkaWcugjbwkcRmX9x3dwruei0re618Drr8wT0=,iv:okiR9IvYCq2IhZ8cRXEviCHKAIXccObLve6eyo4pPzw=,tag:jRiupA/ZUE7qWbCeo+/0AQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
