kind: Secret
ansible_user: ENC[AES256_GCM,data:6SXKEtmy,iv:rzUEAS115CyacCxDsTsBgBn+Jcj2pUKNpIb1GHulMag=,tag:p+3PbH8BMEWBKKbCS8nKGQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+BuP4Slvj84qyQ==,iv:DLoDpLNdfweDc4MOyaM6B2RFz7A6q1ZZ0IswSgF/wOM=,tag:5IdLX4/elzwJYD0tA5F+Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeUt5TnFObVRFWENiSnBE
            UWllaTBRM2sxSG9rR0NxcmxubVowMXZnRVRZCjltK0lOU3BTcmVrTzRoWW9ENnhy
            YnRmSDNnYmtIUTFmZjYvSWZqUUM0aUUKLS0tIEh3Zlc4V1hZT2M5T0JGVU1NWFFS
            MWR6STQ3ZFNFb1NPWE9tbUZ2cEE3aW8KoVVTRR4ijuy2CQjSCVTGHJHjHeyxt8SL
            wizsnPFqWnfQqIC61ul8en7UycEjx9lSAGb3p5d5hiqG4i/TWPK2aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T13:21:37Z"
    mac: ENC[AES256_GCM,data:KzAKUr6Araxqh4YUEWCQTUB3Ew49220fstfxq9oYuvqFz+tUjGTVQEbh01ZslsQdaC6Sjrnr7Y7oinPeYebuPn5jFhSxc610eooui9r/WPCHlymhss2Pc9+8gOKz6HfciaJdv4ZZGyNwIWKJTN6+knKRSEsPKidvk3a5LjihTgI=,iv:iKQ5f6xcdGWecnQgLpDP1hqX40Eeo4xpFLyVbx7bXlQ=,tag:eC3FVlGpNqvosf17NlDCJA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
