kind: Secret
ansible_user: ENC[AES256_GCM,data:Xf9BPnF8,iv:45K846WAQ9/gBW2/Ib23jvfMOtZqvrrQ5djiTmhHvbo=,tag:xjXw0GIqd5e8iYj3kcmn/A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xul+c78kFFAZqg==,iv:zIDAgJlPjvGn/fZuOMbX7PRgVLmdAXblLVo320tUJEI=,tag:OIh4/siYJOJNfnIYm8lHyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWVdWeWtmdEd2eWJLS2Ey
            RENIZTQ1SER3enAwVVlkcndyM0VzYlJKbkE0CmVNVXlJTWVjQjBuZjBrSDBGZmRt
            NytoVnQrQnJsUDh6dnlkM1ZjNjlnR2sKLS0tIHB0bzF4OWNDTnRHV2JPdVR4WDFl
            cGlGTW1MOHZxUUNRdmkxcFpIUWZDVHcKCrhalnfkOl9mOqTJjDfrdIozoaeELCf8
            Qv56GevLVYD/CROZY9nn0aKfpbuKVZneyWPcI8ZSWu925fwGOoAlHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T09:25:47Z"
    mac: ENC[AES256_GCM,data:bchYDzDcBaxly/tktHNGzASzKggz9SbQWxWnPUEOMytueImCVuzqXhMzHnFRBTbMnfAnB6ZZ+TkHovjEOJl1MtvD71uVsbTdUu4LXz9gdj6w3TsGnT7ClzyvRK4Pi3KVlJN1H7rB0Gzj7XSzdpHK+jodwd6m+/04YIfRtmWWaIo=,iv:/0a/ea+n1k8VYo4SMhtII8xqVHmIOaTYaVGqHBAYXRw=,tag:8o6NVFqqxmihGToWQQb0kQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
