kind: Secret
ansible_user: ENC[AES256_GCM,data:ze2a6JIZ,iv:Mb+cDaWJeLQ4oxfPO6z5WO7apErVY2zV4/OR/fDSs2o=,tag:kZsJkyuZE+A9l8cwUOyccw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:azPuT1DboFXF9w==,iv:8gAOSzo51XSynRqlduIy6KydYmJZye9vkF3TBHuxej8=,tag:T0UARhbkUJKhaW1L3lpbSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWGtTZnlMbW9zYWpZczVw
            eTA3aU1KWjAyZ0EvbmpTRTdqQi9Qb2g5eXlZCmMrdGZhOU1meDRhSnFVNTBKci9a
            NjRpLzlDTUlJTVVLbEt2eUpCakU0a2sKLS0tIDNJS2ZWVGloZXZYR21UQTZkNFhT
            VEUza2pvK0FwVFpaVnVoS1RzRXl6Q3cKkOIVV7/AqGHoTWsxAt5ZDade+vvFzobc
            7EgHgvkHgiCDZkcY6IwEREjdUOuXcb0govDw2XFpI5ulLq5fNRf+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T18:26:26Z"
    mac: ENC[AES256_GCM,data:HzDRHLRw/gH82KrqT+3/SdtV5E3umW4zvNUTkM583y9ta4yhH7BRHLdwruGOHE4GpEkp6k6ATK52UYPX9bp3RfIqLOHH0KUi1zyv3h3fiBB4XKNGnYfv6fCbKyyNqKtDZjMC+97fBe2fedBqwxSXQNvLrMGnFxcMiiyjabUam+A=,iv:CeNYeycSLJUTnjUk/RodgtnHsLwfIx/wvbjtSyekWWg=,tag:M+YQuZ/W4ik75n3xfGxGlQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
