kind: Secret
ansible_user: ENC[AES256_GCM,data:9aCfKnQ+,iv:rMJe2mF2zwtm0GfMuRiW2AO92nNJQjxy5S20iSFleDI=,tag:XDDQ3e2qflcdfLRdhvhlNQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:up6N6EUTqGtq6Q==,iv:37LgpyduoewRSSy3kZ69jXmaOX+bgFWKvHjilt8nVF4=,tag:zw8dGcKemKQydS4057yNdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZGNOMEJEbVlaUkY5c2dy
            TXNNNnZZay9oazVtTk9WdVNybXhYbXBxOEYwCjRmQ3NEM3FIdkJVdWdUcDJDWlYr
            M1p6SHhHa2VTMVFlcHcwek9VcDhPMEUKLS0tIHFHaUROdGRXMEtwZkx1Vk5qcnNE
            d0p1OXkwcmtUSUtWeDBCWjNIUTdwSTgK1EGEucrd5+qHaj2IwuJPcW9HAK2hpT4d
            7TDuFZt3y3VtIskRbeCgcWbySk4k7YAWCv3ifwKwD6BUjIki0+NS7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T14:26:08Z"
    mac: ENC[AES256_GCM,data:4HFkmQOV03xLcp/1L9t4NhySRaIaAtTbYmmCDAKq4reEwoO43YTmHxXjXKy0uZBY/bDAmz53F0+jH2qgItL5iF9qbxU/fYLwjcBN8hjWsFMfb495k2Zmi2/jvVKlEc3lgqRTHBoMxOeDYqS59GoByWS/Le6DqDJngoe9tEAkAy8=,iv:4ZfBLd/LH2Jry3hSoUS7QHJx6cWhNE3YrVaB+3Hew50=,tag:csG6OU4tlzz2Y0weyYusxg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
