kind: Secret
ansible_user: ENC[AES256_GCM,data:pByjhJNZ,iv:uJzBUu8gTHNgmqKLhrunmo5PgBgxWe/0hjtulqKnR2E=,tag:axvDKQoRbYW/HrGh35IV3Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ICXODPTQ7Ab/eA==,iv:awg61mI8tycT4ar292LIbpdb8jHfhIx/HjWLrBu9bsU=,tag:I9zwN18lEZf6Jz0fxzkS1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZW9UeFFWejdwRVJHNGJv
            TmdQSGpQdVl4Q09iRmROQ2VVVUM5Zk5ycFdnCitLcWU0aWxqOTQ1OXJzclYvN1lx
            UEZyc1NvbktnMDJOOWZhS0xwMUg3MXMKLS0tIE51WUsrcTFtVGp4RENVOFZmejVM
            VXIzZHZ1TGNaSCtSczBQVldyR2piZTgKeCIuqgH0IVS1QAk9/8GHpHQEMu2R63kU
            TnZup9SAt6/4b/BO4vmTEtPa8mUCLfywRTFQbLsXfH+T1LmXaFfkgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T14:50:01Z"
    mac: ENC[AES256_GCM,data:r8dat8gqeVsiuVm8QLwsNEly1ErSIYg8p3m2b6KX0iP06HJwlDinow84n3yRDZsMGDaBbvpEVXQKZcbd+9exHziOaLKdz53KKprFWnEhZQ13cbJD93/iUsSpu19aC2QazD/biv1GRIZydTs/gyMXmh7X6mpVSgX6n7hHBVA2kPA=,iv:cx+/z6WsIq0b3NcgZ7bI0LJg7U9MJcJdQA8hYZH2/Gk=,tag:HW+KNt89Thu6SP2nIzRIOg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
