kind: Secret
ansible_user: ENC[AES256_GCM,data:bZwgcpei,iv:FsAO8fhGpZr84qYUUuj+0ZhWhqdYhMkxcBk18aHrE+0=,tag:0pjl+E737sjLTZHvOFnQYg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xQ2F+bBWVLc3dQ==,iv:Er5nTpWdYwzbzBuSoHMbtTQgAqL4VPn9bquk3JkZ8tg=,tag:sIGjHptnHSyOkBWQyUJWDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT3o4ZTQrbDluT3FQYlJC
            cnVUbTN4ODBvTHdWaUwxZTU2dHhPampDQVhnCnJlWitxSjFWV1BTZ3d4UTRSdzJ5
            ek1lZThTWVRiZlZyb3NqZ3hWRDVFVGMKLS0tIFhUb3hRRkVMWHBGOEhab1Ava0Yx
            M0pJWXBBL0luR3JLcDlFWEJ0bDJCMjAKyoFUE8ghkGQdOA9XiYiQQngZf4XSs+Tb
            2kHnAZ8Y2ADM2mF09HfAutHG8wcdRlyAblkV/fB4pq8OgYigZNreRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T09:14:25Z"
    mac: ENC[AES256_GCM,data:2QyhmnOPD92y9UwThiAp95gbbZlQI7CMW7BKcGiGPp0QmwxWotRogU/sN0tfBiHhQtVNz9knPu1Qfx21M1FV7ay7KEs4M7cMFKIDHK0eIclO38gL9/KwjE6MqHUhkx3yLj3DjkBrUA+1xqq45A0uGB1Pv7YUf5ScnIWYbHwsi5k=,iv:WrLFQGdCghcGsvVhVStLNZjc3PbyW3qi9C2Qdh/d3Sg=,tag:H0/Z8a5kyiDQt0JJ+dUyYg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
