kind: Secret
ansible_user: ENC[AES256_GCM,data:BdreWfVD,iv:eDhMXaEQF7T2II52sLpgoX5rDiOOif6miCkRo2PZ7/o=,tag:ELBd69OKxXbkMbCpUZROrw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:f6bOx/DVoZIclg==,iv:BB1cpIOB1OJofVq39MjoZh6u2f6Cbh9ULH4FR6OeuW8=,tag:nFvtZalgfhMXv2Wuur8JyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1b205OWJSeFVlY2dFNWJ5
            Q1g1alBwYlI0Y0xhbHMydFgzZ2NYZzRVRkNNCm1OWTRBZnpONWcxNTZJbmFlZ0RR
            MzBIUGZ0VS9MbmdqVUxjcnJMWFREQzQKLS0tIFhJUVFtQk4wbkN4MDcrZ01NRXds
            QlBGQjRjbzRKbmZiaDIwMk9GUjJncGcKubooGVUMcrZkV1bGqJCg+nbaQEKMtfQc
            MfI+Gt/zoSR1XO3VR3rEu9PHivFeXdR4vL6KGTdSotq5YWlBrQg8Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T14:26:08Z"
    mac: ENC[AES256_GCM,data:/z5rN8Gmm/GKTYJ7w5k23cRY/3WNw94KZKXZvYqjqU/1962D+3uEuebpgEpzkw9PXuL3MgBV2A10MuDAXCQS0BQnNyEmGIO6K5ecsbYnUlpGDsA78CTKBP109aUiezRsPfJBI5GcgZt4zwzzbCSQF+Kh4xN96v3lJdiGWw6zBug=,iv:dRpme3hswL9cxDxlbLZ1gsyJrP3HyWUYap1EWIQkFWY=,tag:77FQUmv2+wwxo0frqqcLRg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
