kind: Secret
ansible_user: ENC[AES256_GCM,data:3KxgbeZU,iv:zCq1Jt0NsGCdLFMl5J7gPqUxRZOwBDsL/OZUNK/mDDk=,tag:/kstIQxqsikr4IZzyaqSmw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xHPfDkfFMw8Zhw==,iv:AH1bV3pPuR8DRd1YF9jtQhCEdYxrazpqY6oaTz0KdPw=,tag:v+Gj3QHdyfb9oPwTNHcnXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SklwcjZhNHFMdVo1Y3k5
            L3lBOHdIUERkL2wwa3E4V0lDOE81eTJGKzFzCjJLYitJRjduRWFjNmtQQ01XUHBn
            SW4vSkhaT096L1czeVRXVThvTjNkRTAKLS0tIGJTRGNnLzBLN2Z1UzRBWVRIYTVt
            bTJycE5BT2swenk4Ly9BYjdwVnV4ejAKXP3Ge3DnHw6DnHGSk/fQ2n97JH3P8UrO
            ilQLszZa4wurth2o6wTE5sPMDCtiuHZ2YJwtwpQRSphlasDaVRLXYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T14:50:01Z"
    mac: ENC[AES256_GCM,data:SIOrvjACVUE5q+euUkN2ZXIUq8TNq9B/rwaHQ15DgDWhRdaRE1IjbZ9lchnFSzZDsvbGpiFl4ZX9lyvzO49Rna1qET1bCI9GQf3mjctz1d8SmKNZqKUqk9SxFAM64OUwtQnN+spqfJPI4CFZWlSE2jVA2uVb1qMqMiptbwETkPM=,iv:L23eSarWmiInLdKHOdZynxYbotJRZlYyQyeCDWUY1IE=,tag:KySHrmt/YboP+V0XLrV94A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
