kind: Secret
ansible_user: ENC[AES256_GCM,data:CwU4HwXp,iv:B+x6ro5wPgTY3VMp6xCkKhVedwelTzlnvE6ml1wZtuQ=,tag:oaZ3HRsnBoIXv14fHRgOHg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:sthKXE6VDAyC3g==,iv:9akElNs8JB+RxMx09htx4Ad68OZRu45tDShE+p26ACA=,tag:CvQo3D58AzOF0Up7L4363g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWWE2Y0RGQVdnVFdIUXpq
            cTUxM0pxN3B0R204d3pDcXZxUGh3RFA2c0VZCmh2T3ZZSUh5aFpPdXI0Z0xqNWFv
            RkUxbmMxaTcvYis2amNBSEZ3V096UGcKLS0tIGtlLzFCNXhUeUJjSTNWaW1wU1pZ
            bFV6R0Z1RkdxOGtBMXlHWnN0bVduQW8Km8YrN8htnyljImrFr/sJOUhJu2QfGUB8
            7eco6w8q/MEZ0fc6lqARLc4HXg2UaPjbetCtzGsDS0nC5I1IrTAwWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T20:21:38Z"
    mac: ENC[AES256_GCM,data:9EoyUhPYkDfUSrkS5ulWQAUs794Puu5DCTqeEK5IGFe5v/UP+MEKtQrvZRfFNMhmaX7gMA/qAYFkjixPwAEjXLUFbkrWjk1U7/nMUpanO2oyosFV5OpF5gAUAjY0YSyTfLzIU6FiIHXxTvy6PhXRO/VkN07WhMW9Lg/gYwbz4Us=,iv:t34cj7SNZEng2YVa0dBUKRDbU5+iYev+dOKdGEtMSuE=,tag:HvLsQMQkLVGCpM3vH4/mDQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
