kind: Secret
ansible_user: ENC[AES256_GCM,data:2VDjWUeo,iv:aNu9KJ7QYpFcNjJeJ9VXRq9sJTDlq4nD6kf/ri9O0ls=,tag:LjqMeyr5oRpug2h7v+eQ7Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:o9JLOr/ds1ptIw==,iv:pUY1dxdjV0N4vROTW/1mKSnAXSJBeH4vDVP79y7p2xE=,tag:0qR/anoe/raJjrdfexITMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSGtvYzZtc0JNTU40azEr
            OGJtWlFERGFvL1piZFM5SDNGZEZpOGNlZVZJCldMTjdoK0tYbXFqL3daRlZCVUUy
            UHZXQkhobnJUYVhQeExGRmVCTGt1a1UKLS0tIEZnMTlqcWNSYzhNbVAxWC8rVXU0
            NEQ2RXJid2tUL0VHT2M1bmlYR3VtdHcKU6IU9nytKi7byTTbnxnC5k6Dt9CCSAx9
            7Na3xyadKiIgeTh0pV4EZvO0IBzQBzh1JfTuTVeGTgMhi8yS+CstQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T14:36:46Z"
    mac: ENC[AES256_GCM,data:wDl0xQUTW2YoKP3LHfQmg3XaQYqd08PU9/qOIg2R1XQ5VrMs1qY48SIKOADRDgaP1OahZcGlET+Sz6/CTh22rcox6IQAeUPSKzqQC/Wl5/Ow5e38AbdS0p5GfkfKb8X8wLjTxYDofEeZkCIPBYbJOhaaNq8DNAiA8YzNPf0Y0s4=,iv:AJ10L+ji7DmDsNoUJCmujVH74AOVGnjAGL0+ttSuyTc=,tag:gntFARNQ+kNgsqP0DbFGqw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
