kind: Secret
ansible_user: ENC[AES256_GCM,data:8uhlb4yg,iv:o1e+R1Zt2qE6z9cMcLGfDzOhNNroGBi/GyZuwlBmw9U=,tag:XP15W0vnIRUJbY1EdeBPHw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:251mdbvd5p6pFg==,iv:Frd0HkXcwp7O8ybcrGLa7VxhBicg8VihqO3iQmoSEfs=,tag:NoP3eV3diD8Zc2tb5X9sqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMm9UU1k3YUdOTGV4NFhT
            TXVSenRvK0hZYWZ1aGxBWDNURnZMWlFmU1RFClZqUFhIS0lVdlI0dHFvbmVIV1JM
            alpiYzVNMjBtWC8yTjR6S094c3JIWjgKLS0tIHVpdHdZMTVwMmJ5a3FkUHV3MEFv
            Q1NhcHRWV3RTUXhqY0lTZEI4NlcxZ00K7juqpHfZL62b/P14X7k8j070HPQfIMPE
            Egz1924z+2OzWnD0LArIE8mbcsTMUO0EH89ir8xM1EQIH7Qi0awAng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T12:15:46Z"
    mac: ENC[AES256_GCM,data:mmHn62yQ/h1QP/ictcsKLsFBSb91AjBSGRCacpvsOj5aJJ44Jha328z6xDb77iq0xB4Ieo4Jr85B9VacwtxBccoLhWd+sLGl+uUNCik4tUfLpXE+K6kcBFY2JVgV7UeFzDh5qtf4MFvFDQJEa9FHZAhZukmwNOoHTLyLElEg5c8=,iv:+zXHmuk3HhuzcvWphZZ/u+ojAK7hqqEzJ/2PTlTdCvw=,tag:dYwbM771tC86PTQEiUX8mg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
