---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        #external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        #nginx.ingress.kubernetes.io/auth-signin: http://oauth2.${SECRET_DOMAIN}/oauth2/start
        #nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
        #external-dns/is-public: "true"
        hajimari.io/enable: "true"
      #hosts:
      #- host: "longhorn.${SECRET_DOMAIN}"
      host: "longhorn.${SECRET_DOMAIN}"
      tls:
        true
        #paths:
        #  - path: /
        #    pathType: Prefix
      #tls:
      #  - hosts:
      #      - "longhorn.${SECRET_DOMAIN}"
      #    secretName: "longhorn-tls"

    #csi:
    #  kubeletRootDir: /var/lib/k0s/kubelet

    # defaultSettings:
    #   #defaultDataPath: /mnt/dati/kubernetes/longhorn
    #   replicaSoftAntiAffinity: true
    #   replicaZoneSoftAntiAffinity: true
    #   createDefaultDiskLabeledNodes: false
    #   defaultReplicaCount: 1
    #   #defaultLonghornStaticStorageClass: longhorn-static-storageclass
    #   guaranteedEngineCPU: 0.10
    # persistence:
    #   defaultClassReplicaCount: 1
