# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZjdgddST564XCNazJHAN7EDPbIspWxPcCIZkX9mhyjMwx1oApZ56NQ==,iv:lb83wuHbvCJUxcMekaEKVlOYruDNC7PbetHinUqBESI=,tag:XrllRKvtJc/icAvc1tjZvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWW1SSEl3SjVsNjl2eWM3
            WFE5dXJOWVNBWFN1dmNBcGE5VVpDSzMwNzI0CmdaQXl3aU5KQkFEcDhVanhCcWc5
            T1VEU2FrVFY0bGVaUFh4SkMzQzFtblEKLS0tIHJJbGZ1elRVZVc1YnQxTWRpZzBo
            Z0hON2VJOFZ0ejRaTVhScmt6ZFhlWGMKLV6K8hfksmIquh5CJtNemmBDYwW/n/QQ
            /XUOes4+HLRNOAX0ZUQ27CW7yHnukiaEwD+y769TawYcDBSoP5cypw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T16:29:49Z"
    mac: ENC[AES256_GCM,data:jpCMR6qxQE2HxmINPuh0TsuLJLYo/h1gYHnbQKlflvZ15nvQ4wYBUqn3P3/gyFGxd40wQMBjha0U2w3Uh4IWLGaI2w2uIWRofIPrI8z/FUVUIjGmcbj/8Gld3zcjnH+09LmcMREs45ne8Lgk5RZkVaFHmdJs29e6PGkPG2TqQVI=,iv:xduby/zv8hyhJMHabjPATumjVOeT8Ucz5yR0Xkkmka0=,tag:MwBm6RQhjVXePpaP4kZqgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
