# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:omAul/DSDTZAhg8M/ju6qqpUCVClVDAlY3M2EEp5jSTjOxs8bz9s1A==,iv:OMAXHdf4WmxdJ5FisaSHd8ikb3XTTZej4GR4SMklqkA=,tag:fxZUoEPdQ7aKXgGLIl9uYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5uandym7aydp8qltgek40d0sxhe95wq5cpzdakvnrfnua2r0e2qcjf0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNTc0aHZUc1hNOG1RZ0N3
            ZlcvenhlM3Z1ZGtxUmh4RUF5ZnMwc0FCN3dZCjN6aGFxRDkxbVhRQ21NM0MvT0tO
            Zk95ZWdNeHFVSTFaSWM1MXd1WlhXaU0KLS0tIFZvN0NEd3JQN3phOVRwY0liRTNu
            cENTS05LNU5WMzV1U2RWYjI0dmlYamsKuFiG3V5jLlt3QRWwXN1Ms7KhttyvqYb1
            EebNwcbRgehzUCH+TVOlM4mVftFSj5A6ZY9kCFaW47pBMjyTrRj8kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T20:21:38Z"
    mac: ENC[AES256_GCM,data:THQy85QNpLuoTORRXB0wD9Icu1movr16w3c82pLzAImtA1DUWVDIqK8WO0xgsUIFcEqlD2OmhIR84i7V3stO9H0K0/5vg7ZkJTz3gIZ6Csts3hh0rQe68fk12v1o6CJFoHBf5eNolnruiA6N5VkfDoLdg01/rKTooaCAkeOEoy4=,iv:ho3hhbcqNAm4kAmarg8Ohglp5TJHXo3gjsvuH9K4t/U=,tag:2fsji1AfLzwaSW+LRH6L5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
